# Generated by Django 4.1 on 2022-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pt_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="my_uid_rule",
            field=models.CharField(
                default='//a[contains(@class,"_Name") and contains(@href,"userdetails.php?id=")]/@href',
                max_length=128,
                verbose_name="用户ID",
            ),
        ),
    ]
