# Generated by Django 4.1 on 2022-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="url",
            field=models.URLField(
                default="", help_text='请保留网址结尾的"/"', unique=True, verbose_name="站点网址"
            ),
        ),
    ]
