# Generated by Django 4.1 on 2022-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0002_alter_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='sign_in_info',
            field=models.CharField(default='', max_length=256, verbose_name='信息'),
        ),
    ]
