# Generated by Django 4.1 on 2022-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0003_signin_sign_in_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category_rule',
            field=models.CharField(default='.//td[@class="rowfollow nowrap"][1]/a[1]/img/@title', max_length=128, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='site',
            name='completers_rule',
            field=models.CharField(default='.//a[contains(@href,"viewsnatches.php?id=")]//text()', max_length=128, verbose_name='完成人数'),
        ),
        migrations.AlterField(
            model_name='site',
            name='download_url_rule',
            field=models.CharField(default='.//a[contains(@href,"download.php?id=") and contains(@href,"passkey")]/@href', max_length=128, verbose_name='详情页种子链接'),
        ),
        migrations.AlterField(
            model_name='site',
            name='leechers_rule',
            field=models.CharField(default='.//a[contains(@href,"#leechers")]/text()', max_length=128, verbose_name='下载人数'),
        ),
        migrations.AlterField(
            model_name='site',
            name='magnet_url_rule',
            field=models.CharField(default='.//td/a[contains(@href,"download.php?id=")]/@href', max_length=128, verbose_name='主页下载链接'),
        ),
        migrations.AlterField(
            model_name='site',
            name='peer_speed_rule',
            field=models.CharField(default='.//tr/td[7]/nobr/text()', max_length=128, verbose_name='平均下载速度'),
        ),
        migrations.AlterField(
            model_name='site',
            name='record_count_rule',
            field=models.CharField(default='.//td[3]/text()', help_text='提取做种列表中文件大小计算总量', max_length=128, verbose_name='做种大小列表'),
        ),
        migrations.AlterField(
            model_name='site',
            name='sale_rule',
            field=models.CharField(default='.//div/img[contains(@class,"pro_")]/@alt', max_length=128, verbose_name='促销信息'),
        ),
        migrations.AlterField(
            model_name='site',
            name='seeders_rule',
            field=models.CharField(default='.//a[contains(@href,"#seeders")]/text()', max_length=128, verbose_name='做种人数'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title_rule',
            field=models.CharField(default='.//td[@class="embedded"]/a/following::text()[1]', max_length=128, verbose_name='种子标题'),
        ),
    ]
