# Generated by Django 4.1 on 2022-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0004_alter_site_category_rule_alter_site_completers_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentinfo',
            name='hr',
            field=models.BooleanField(default=True, help_text='绿色为通过或无需HR考核', verbose_name='H&R考核'),
        ),
    ]
