# Generated by Django 4.1 on 2022-09-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0005_alter_torrentinfo_hr"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="notice_rule",
            field=models.CharField(
                default='//a[@href="index.php"]/font/text()[1]',
                help_text="获取新公告",
                max_length=128,
                verbose_name="公告规则",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="mailbox_rule",
            field=models.CharField(
                default='//a[@href="messages.php"]/font/text()',
                help_text="获取新邮件",
                max_length=128,
                verbose_name="邮件规则",
            ),
        ),
    ]
