# Generated by Django 4.1 on 2022-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0006_site_notice_rule_alter_site_mailbox_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestatus',
            name='downloaded',
            field=models.IntegerField(default=0, verbose_name='下载量'),
        ),
        migrations.AlterField(
            model_name='sitestatus',
            name='uploaded',
            field=models.IntegerField(default=0, verbose_name='上传量'),
        ),
    ]
