# Generated by Django 4.1 on 2022-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0007_alter_sitestatus_downloaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="my_passkey_rule",
            field=models.CharField(
                default='//td[contains(text(),"密钥")]/following-sibling::td[1]/text()',
                max_length=128,
                verbose_name="Passkey",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="my_uid_rule",
            field=models.CharField(
                default='//a[contains(@class,"_Name") and contains(@href,"userdetails.php?id=")]/@href',
                max_length=128,
                verbose_name="用户ID",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="page_control_panel",
            field=models.CharField(
                default="usercp.php", max_length=64, verbose_name="控制面板"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="my_level_rule",
            field=models.CharField(
                default='//a[contains(@class,"_Name") and contains(@href,"userdetails.php?id=1")]/@class',
                max_length=128,
                verbose_name="用户等级",
            ),
        ),
    ]
