# Generated by Django 4.1 on 2022-09-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0008_site_my_passkey_rule_site_my_uid_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloader',
            name='category',
            field=models.CharField(choices=[('Tr', 'Transmission'), ('Qb', 'qBittorrent')], default='Qb', max_length=128, verbose_name='下载器'),
        ),
        migrations.AlterField(
            model_name='site',
            name='mailbox_rule',
            field=models.CharField(default='//a[@href="messages.php"]/font[contains(text(),"条")]/text()[1]', help_text='获取新邮件', max_length=128, verbose_name='邮件规则'),
        ),
        migrations.AlterField(
            model_name='site',
            name='notice_rule',
            field=models.CharField(default='//a[@href="index.php"]/font[contains(text(),"条")]/text()[1]', help_text='获取新公告', max_length=128, verbose_name='公告规则'),
        ),
    ]
