# Generated by Django 4.1 on 2022-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0009_alter_downloader_category_alter_site_mailbox_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='completers_rule',
            field=models.CharField(default='.//a[contains(@href,"viewsnatches")]//text()', max_length=128, verbose_name='完成人数'),
        ),
        migrations.AlterField(
            model_name='site',
            name='hash_rule',
            field=models.CharField(default='//td/b[contains(text(),"Hash")]/following::text()[1]', max_length=128, verbose_name='种子HASH'),
        ),
        migrations.AlterField(
            model_name='site',
            name='my_hr_rule',
            field=models.CharField(default='//a[@href="myhr.php"]//text()', max_length=128, verbose_name='H&R'),
        ),
        migrations.AlterField(
            model_name='site',
            name='sale_expire_rule',
            field=models.CharField(default='.//img[contains(@class,"pro_")]/following::font/span/@title', max_length=128, verbose_name='促销时间'),
        ),
        migrations.AlterField(
            model_name='site',
            name='sp_full',
            field=models.FloatField(default=100, help_text='时魔满魔', verbose_name='满魔'),
        ),
    ]
