# Generated by Django 4.1 on 2022-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_site", "0010_alter_site_completers_rule_alter_site_hash_rule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mysite",
            name="passkey",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="PassKey"
            ),
        ),
    ]
