# Generated by Django 4.1 on 2022-09-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0011_alter_mysite_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='invitation_rule',
            field=models.CharField(default='//span/a[contains(@href,"invite.php?id=")]/following-sibling::text()[1]', max_length=128, verbose_name='邀请资格'),
        ),
    ]
