# Generated by Django 4.1 on 2022-09-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0012_alter_site_invitation_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='my_level_rule',
            field=models.CharField(default='//table[@id="info_block"]//span/a[contains(@class,"_Name") and contains(@href,"userdetails.php?id=")]/@class', max_length=128, verbose_name='用户等级'),
        ),
        migrations.AlterField(
            model_name='site',
            name='my_uid_rule',
            field=models.CharField(default='//table[@id="info_block"]//span/a[contains(@class,"_Name") and contains(@href,"userdetails.php?id=")]/@href', max_length=128, verbose_name='用户ID'),
        ),
    ]
