# Generated by Django 4.1 on 2022-09-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_site', '0013_alter_site_my_level_rule_alter_site_my_uid_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='sale_expire_rule',
            field=models.CharField(default='.//img[contains(@class,"free")]/following::font/span/@title', max_length=128, verbose_name='促销时间'),
        ),
        migrations.AlterField(
            model_name='site',
            name='sale_rule',
            field=models.CharField(default='.//img[contains(@class,"free")]/@alt', max_length=128, verbose_name='促销信息'),
        ),
    ]
