# Generated by Django 4.1 on 2022-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pt_site", "0014_alter_site_sale_expire_rule_alter_site_sale_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="sale_expire_rule",
            field=models.CharField(
                default='.//img[contains(@class,"free")]/following-sibling::font/span/@title',
                max_length=128,
                verbose_name="促销时间",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="title_rule",
            field=models.CharField(
                default='.//a[contains(@href,"detail")]/parent::td/text()[last()]',
                max_length=128,
                verbose_name="种子标题",
            ),
        ),
    ]
